<?php $initial = mb_strtoupper(mb_substr($config['name'], 0, 1)); ?>
<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Export &middot; <?= $e($config['name']) ?></title><link rel="stylesheet" href="/frontend/view/stylesheet/app.css?v=<?= @filemtime(dirname(__DIR__, 4) . '/frontend/view/stylesheet/app.css') ?: 1 ?>"><style>:root{--brand:<?= $e($config['accent']) ?>}</style><script type="module" src="/admin/view/javascript/export.js?v=<?= @filemtime(dirname(__DIR__, 4) . '/admin/view/javascript/export.js') ?: 1 ?>"></script></head>
<body class="editor-body"><?php require __DIR__ . '/../common/header.php'; ?>
<main class="admin-dashboard"><header class="page-header"><div><span class="panel-eyebrow">Content Studio</span><h1>Export documentation</h1><p>Build a portable static bundle from the browser or use the equivalent command line.</p></div><a class="button secondary-button" href="/admin">Return to overview</a></header>
<?php if ($message): ?><p class="form-success" role="status"><?= $e($message) ?></p><?php endif; ?><?php if ($error): ?><p class="form-error" role="alert"><?= $e($error) ?></p><?php endif; ?>
<?php if ($download_file): ?><section class="download-ready"><div><strong>Your export is ready</strong><span>The archive is stored outside the public web root and deleted after download.</span></div><a class="button" href="/admin/export/download?file=<?= rawurlencode($download_file) ?>">Download ZIP</a></section><?php endif; ?>
<div class="export-grid"><section class="export-card"><div class="export-card-head"><span class="export-icon">↓</span><div><strong>Build a ZIP</strong><p>Select exactly what the archive may contain.</p></div></div>
<?php if ($zip_available): ?><form method="post" class="export-form" data-export-form><input type="hidden" name="csrf" value="<?= $e($csrf) ?>"><div class="profile-options"><label><input type="radio" name="profile" value="public" checked><span><strong>Public</strong><small>Published public pages only. Private and draft pages are excluded.</small></span></label><label><input type="radio" name="profile" value="sanitized"><span><strong>Sanitized</strong><small>Includes private pages but redacts recognized secret assignments.</small></span></label><label><input type="radio" name="profile" value="private"><span><strong>Private</strong><small>Includes private pages and may contain live credentials.</small></span></label></div><label class="export-ack" data-private-ack hidden><input type="checkbox" name="acknowledge_secrets" value="1"><span>I understand this archive may contain live credentials and must remain private.</span></label><button class="button" type="submit">Build export</button></form><?php else: ?><div class="export-unavailable"><strong>ZIP support is unavailable</strong><p>Use the CLI commands shown beside this panel.</p></div><?php endif; ?></section>
<section class="export-card cli-card"><div class="export-card-head"><span class="export-icon">&gt;_</span><div><strong>Command-line equivalent</strong><p>Useful for deployments and automated backups.</p></div></div><div class="cli-commands"><div><span>Public</span><code>php bin/docs build build --profile=public</code></div><div><span>Sanitized</span><code>php bin/docs build sanitized-build --profile=sanitized</code></div><div><span>Private</span><code>php bin/docs build private-build --profile=private --acknowledge-secrets</code></div></div><p class="export-note">Every build contains `export-profile.txt`, `integrity.sha256`, static HTML, source Markdown, search data, and LLM-friendly output appropriate to the selected profile.</p></section></div>
</main></body></html>
