<?php
$sections = $sections ?? [];
$current_section = $current_section ?? null;
$section_icon = static function (?string $name, string $class = ''): string {
    $class = 'h-3 w-3 shrink-0 opacity-70 ' . $class;
    $paths = match ($name) {
        'home' => '<path d="M3 10.5 12 3l9 7.5"/><path d="M5 9.5V21h14V9.5"/>',
        'server', 'proxmox' => '<rect x="3" y="4" width="18" height="6" rx="1.5"/><rect x="3" y="14" width="18" height="6" rx="1.5"/><path d="M7 7h.01M7 17h.01"/>',
        'guides' => '<path d="M4 5.5A2.5 2.5 0 0 1 6.5 3H11v16H6.5A2.5 2.5 0 0 0 4 21.5z"/><path d="M20 5.5A2.5 2.5 0 0 0 17.5 3H13v16h4.5a2.5 2.5 0 0 1 2.5 2.5z"/>',
        default => '<path d="M3 6.5A1.5 1.5 0 0 1 4.5 5H9l2 2h8.5A1.5 1.5 0 0 1 21 8.5v9a1.5 1.5 0 0 1-1.5 1.5h-15A1.5 1.5 0 0 1 3 17.5z"/>',
    };

    return '<svg class="' . trim($class) . '" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">' . $paths . '</svg>';
};
$render_tree = function (array $nodes, string $current, int $depth = 0) use (&$render_tree, $e): string {
    $html = '<ul class="m-0 list-none p-0' . ($depth > 0 ? ' relative mb-[9px] ms-3 mt-[3px] ps-3 before:absolute before:inset-y-1 before:[inset-inline-start:0] before:w-px before:bg-[var(--border)]' : '') . '" data-nav-list>';
    foreach ($nodes as $node) {
        $active = $node['url'] === $current;
        if ($node['type'] === 'folder') {
            $inside = $current === $node['url'] || str_starts_with($current, rtrim($node['url'], '/') . '/');
            $open = $inside || empty($node['collapsed']);
            $label = !empty($node['landing']) ? '<a class="min-w-0 flex-1 overflow-hidden text-ellipsis whitespace-nowrap' . ($active ? ' text-[var(--brand-strong)]' : '') . '" href="' . $e($node['url']) . '"' . ($active ? ' aria-current="page"' : '') . (!empty($node['private']) ? ' data-no-prefetch' : '') . '>' . $e($node['title']) . '</a>' : '<span class="min-w-0 overflow-hidden text-ellipsis">' . $e($node['title']) . '</span>';
            $html .= '<li class="my-px"><details class="group" data-nav-folder="' . $e($node['url']) . '" ' . ($open ? 'open' : '') . '><summary class="flex min-h-9 cursor-pointer list-none select-none items-center gap-2 rounded-[var(--radius-sm)] px-[9px] py-[7px] text-sm font-[620] leading-[1.4] text-[var(--text)] hover:bg-[var(--surface-subtle)] [&::-webkit-details-marker]:hidden [[data-density=compact]_&]:min-h-[27px] [[data-density=compact]_&]:py-1 [@media(pointer:coarse)]:min-h-10"><span class="h-1.5 w-1.5 shrink-0 -rotate-45 border-b-[1.5px] border-r-[1.5px] border-current text-[var(--faint)] transition-transform duration-150 group-open:rotate-45" aria-hidden="true"></span>' . $label . '</summary>';
            $html .= $render_tree($node['children'], $current, $depth + 1) . '</details></li>';
        } else {
            $badge = !empty($node['private']) ? '<span class="ms-auto inline-flex items-center rounded-full border border-[var(--border)] bg-[var(--surface-subtle)] px-[5px] py-[3px] text-[11px] font-[650] leading-none tracking-[.02em] text-[var(--muted)]">Private</span>' : (!empty($node['draft']) ? '<span class="ms-auto inline-flex items-center rounded-full border border-[var(--border)] bg-[var(--surface-subtle)] px-[5px] py-[3px] text-[11px] font-[650] leading-none tracking-[.02em] text-[var(--muted)]">Draft</span>' : '');
            $active_classes = $active ? ' relative bg-[var(--brand-soft)] font-[620] text-[var(--brand-strong)] before:absolute before:[inset-inline-start:0] before:h-[15px] before:w-0.5 before:rounded before:bg-[var(--brand)]' : '';
            $html .= '<li class="my-px"><a class="flex min-h-9 cursor-pointer select-none items-center gap-2 rounded-[var(--radius-sm)] px-[9px] py-[7px] text-sm leading-[1.4] text-[var(--muted)] hover:bg-[var(--surface-subtle)] hover:text-[var(--text)] [[data-density=compact]_&]:min-h-[27px] [[data-density=compact]_&]:py-1 [@media(pointer:coarse)]:min-h-10' . $active_classes . '" href="' . $e($node['url']) . '"' . ($active ? ' aria-current="page"' : '') . (!empty($node['private']) ? ' data-no-prefetch' : '') . '><span class="min-w-0 overflow-hidden text-ellipsis">' . $e($node['title']) . '</span>' . $badge . '</a></li>';
        }
    }
    return $html . '</ul>';
};
$page_title = $title === $config['name'] ? $title : $title . ' · ' . $config['name'];
$initial = mb_strtoupper(mb_substr($config['name'], 0, 1));
$asset_version = static fn (string $asset): string => $asset . '?v=' . (@filemtime((defined('DIR_ROOT') ? DIR_ROOT : '') . ltrim($asset, '/')) ?: 1);
$extension_assets = $config['extension_assets']['public'] ?? ['styles' => [], 'scripts' => []];
?>
<!doctype html>
<html class="scroll-smooth scroll-pt-9 bg-[var(--canvas)] max-[840px]:scroll-pt-[calc(var(--header)+24px)] max-[840px]:[--header:54px]" lang="<?= $e($config['language'] ?? 'en') ?>" dir="<?= $e($config['direction'] ?? 'ltr') ?>" data-density="<?= $e($config['theme']['density'] ?? 'comfortable') ?>">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <title><?= $e($page_title) ?></title>
  <meta name="description" content="<?= $e($description ?: $config['tagline']) ?>">
  <meta name="color-scheme" content="light dark">
  <meta name="theme-color" content="#ffffff" media="(prefers-color-scheme: light)">
  <meta name="theme-color" content="#0b0b0f" media="(prefers-color-scheme: dark)">
  <?php if ($canonical_path !== '' && $config['base_url'] !== ''): ?><link rel="canonical" href="<?= $e($config['base_url'] . $canonical_path) ?>"><?php endif; ?>
  <link rel="icon" href="/favicon.svg" type="image/svg+xml">
  <link rel="stylesheet" href="<?= $e($asset_version('/frontend/view/stylesheet/front.min.css')) ?>">
  <?php foreach ($extension_assets['styles'] as $asset): ?><link rel="stylesheet" href="<?= $e($asset_version($asset)) ?>"><?php endforeach; ?>
  <style>:root{--brand:<?= $e($config['accent']) ?>;--radius:<?= ['small' => '6px', 'large' => '14px'][$config['theme']['radius'] ?? 'medium'] ?? '10px' ?>;--content:<?= ['narrow' => '680px', 'wide' => '880px'][$config['theme']['content_width'] ?? 'normal'] ?? '768px' ?>}</style>
  <script nonce="<?= $e($csp_nonce ?? '') ?>">try{const t=localStorage.getItem('lightdocs-theme')||<?= json_encode($config['theme']['default_theme'] ?? 'system') ?>;if(t&&t!=='system')document.documentElement.dataset.theme=t;if(localStorage.getItem('lightdocs-sidebar')==='collapsed')document.documentElement.dataset.sidebarCollapsed='true';const r=JSON.parse(localStorage.getItem('lightdocs-reading-preferences')||'{}');if(r.text_size)document.documentElement.dataset.readingTextSize=r.text_size;if(r.content_width)document.documentElement.dataset.readingWidth=r.content_width;const l=r.layout||(r.focus?'focus':'standard');document.documentElement.dataset.readerLayout=l;if(l==='focus')document.documentElement.dataset.readerFocus='true'}catch{}</script>
  <script type="module" src="<?= $e($asset_version('/frontend/view/javascript/app.js')) ?>"></script>
  <?php foreach ($extension_assets['scripts'] as $asset): ?><script type="module" src="<?= $e($asset_version($asset)) ?>"></script><?php endforeach; ?>
</head>
<body class="m-0 bg-[var(--canvas)] text-[15px] leading-[1.62] tracking-[-.006em] text-[var(--text)] antialiased print:bg-white selection:bg-[color-mix(in_srgb,var(--brand)_22%,transparent)] [&_button]:touch-manipulation [&_:focus-visible]:rounded-sm [&_:focus-visible]:outline-2 [&_:focus-visible]:outline-offset-2 [&_:focus-visible]:outline-[var(--brand)] [&_kbd]:inline-flex [&_kbd]:min-h-5 [&_kbd]:items-center [&_kbd]:justify-center [&_kbd]:rounded-[5px] [&_kbd]:border [&_kbd]:border-b-2 [&_kbd]:border-[var(--border-strong)] [&_kbd]:bg-[var(--surface)] [&_kbd]:px-[5px] [&_kbd]:py-px [&_kbd]:font-mono [&_kbd]:text-[11px] [&_kbd]:leading-none [&_kbd]:text-[var(--muted)]">
<a class="fixed [inset-inline-start:12px] top-[-70px] z-[200] rounded-md bg-[var(--brand)] px-3.5 py-2 text-sm font-semibold text-white shadow-xl focus:top-3" href="#main-content">Skip to content</a>
<a class="fixed [inset-inline-start:144px] top-[-70px] z-[200] rounded-md bg-[var(--brand)] px-3.5 py-2 text-sm font-semibold text-white shadow-xl focus:top-3" href="#sidebar">Skip to navigation</a>
<div class="pointer-events-none fixed inset-x-0 top-0 z-[110] h-0.5 bg-[color-mix(in_srgb,var(--brand)_12%,transparent)]" data-reading-progress aria-hidden="true"><span class="block h-full w-full scale-x-0 bg-[var(--brand)] shadow-[0_1px_5px_color-mix(in_srgb,var(--brand)_48%,transparent)] transition-transform duration-75"></span></div>
<header class="fixed inset-x-0 top-0 z-50 h-[var(--header)] border-b border-[var(--border)] bg-[color-mix(in_srgb,var(--bg)_88%,transparent)] backdrop-blur-[18px] min-[841px]:hidden print:hidden" data-site-header>
  <div class="flex h-full items-center justify-between gap-3 px-3.5">
    <div class="flex min-w-0 items-center">
      <button class="hidden h-[34px] w-[34px] place-items-center rounded-[var(--radius-sm)] p-0 text-[var(--muted)] hover:bg-[var(--surface-hover)] hover:text-[var(--text)] max-[840px]:grid" type="button" data-menu-toggle aria-label="Open navigation" aria-expanded="false" aria-controls="sidebar"><span class="relative h-[1.5px] w-4 rounded bg-current before:absolute before:-top-[5px] before:left-0 before:h-[1.5px] before:w-4 before:rounded before:bg-current after:absolute after:-bottom-[5px] after:left-0 after:h-[1.5px] after:w-4 after:rounded after:bg-current" aria-hidden="true"></span></button>
      <a class="flex items-center gap-2 whitespace-nowrap text-[var(--text-strong)]" href="/"><span class="grid h-[29px] w-[29px] shrink-0 place-items-center rounded-md bg-[var(--brand)] text-[13px] font-extrabold text-white shadow-sm"><?= $e($initial) ?></span><span class="min-w-0 max-w-[180px] overflow-hidden text-ellipsis whitespace-nowrap max-[540px]:max-w-[130px]" data-brand-name><?= $e($config['name']) ?></span></a>
    </div>
    <button class="grid h-[38px] w-[38px] place-items-center rounded-[var(--radius-md)] text-[var(--muted)] hover:bg-[var(--surface-hover)] hover:text-[var(--text)]" type="button" data-open-search aria-label="Search documentation"><span class="relative inline-block h-3.5 w-3.5 rounded-full border-[1.6px] border-current text-[var(--faint)] after:absolute after:-bottom-0.5 after:-right-1 after:h-[1.6px] after:w-[5px] after:rotate-45 after:rounded after:bg-current" aria-hidden="true"></span></button>
  </div>
</header>
<div class="mx-auto grid max-w-[1900px] grid-cols-[var(--sidebar)_minmax(0,1fr)_var(--toc)] pe-5 max-[1200px]:grid-cols-[264px_minmax(0,1fr)] max-[1200px]:pe-2.5 max-[840px]:block max-[840px]:pt-[var(--header)] max-[840px]:pe-0 max-[540px]:px-4 print:block print:max-w-none print:p-0 min-[841px]:[[data-sidebar-collapsed=true]_&]:grid-cols-[64px_minmax(0,1fr)_var(--toc)] min-[841px]:[[data-reader-layout=notebook]_&]:grid-cols-[220px_minmax(0,1fr)] min-[841px]:[[data-reader-focus=true]_&]:!grid-cols-[minmax(0,1fr)] min-[841px]:[[data-reader-focus=true]_&]:px-5">
  <div class="fixed inset-0 z-[60] hidden bg-[rgba(5,5,8,.58)] backdrop-blur-sm" data-sidebar-backdrop data-close-sidebar></div>
  <aside id="sidebar" class="sticky top-0 flex h-screen h-dvh flex-col overflow-hidden px-[17px] pb-3.5 pt-[18px] [scrollbar-color:var(--border)_transparent] [scrollbar-width:thin] max-[840px]:fixed max-[840px]:inset-y-0 max-[840px]:[inset-inline-start:0] max-[840px]:z-[70] max-[840px]:w-[min(320px,88vw)] max-[840px]:[transform:translateX(-100%)] max-[840px]:bg-[var(--surface)] max-[840px]:p-3.5 max-[840px]:shadow-[var(--shadow-lg)] max-[840px]:transition-transform max-[840px]:duration-200 max-[840px]:data-[open=true]:[transform:translateX(0)] rtl:max-[840px]:[transform:translateX(100%)] rtl:max-[840px]:data-[open=true]:[transform:translateX(0)] print:hidden min-[841px]:[[data-sidebar-collapsed=true]_&]:px-2.5 min-[841px]:[[data-reader-layout=notebook]_&]:px-3 min-[841px]:[[data-reader-focus=true]_&]:hidden" data-open="false" aria-label="Documentation navigation">
    <div class="flex min-h-10 items-center justify-between px-1 pb-2.5 pt-0.5 min-[841px]:[[data-sidebar-collapsed=true]_&]:justify-center" data-sidebar-head>
      <a class="flex items-center gap-2 whitespace-nowrap text-[var(--text-strong)]" href="/"><span class="grid h-[29px] w-[29px] shrink-0 place-items-center rounded-md bg-[var(--brand)] text-[13px] font-extrabold text-white shadow-sm"><?= $e($initial) ?></span><span class="min-w-0 overflow-hidden text-ellipsis whitespace-nowrap min-[841px]:[[data-sidebar-collapsed=true]_&]:hidden" data-brand-name><?= $e($config['name']) ?></span></a>
      <button class="hidden h-[34px] w-[34px] place-items-center rounded-[var(--radius-sm)] p-0 text-[var(--muted)] hover:bg-[var(--surface-hover)] hover:text-[var(--text)] max-[840px]:grid" type="button" data-sidebar-close data-close-sidebar aria-label="Close navigation"><span aria-hidden="true">×</span></button>
    </div>
    <button class="mb-4 grid h-[38px] w-full grid-cols-[16px_1fr_auto] items-center gap-[9px] rounded-[var(--radius-md)] border border-[var(--border)] bg-[var(--surface)] py-0 pl-[11px] pr-[7px] text-left text-[var(--muted)] shadow-[0_1px_1px_rgba(15,15,18,.03)] hover:border-[var(--border-strong)] hover:bg-[var(--surface-hover)] hover:text-[var(--text)] min-[841px]:[[data-sidebar-collapsed=true]_&]:mx-auto min-[841px]:[[data-sidebar-collapsed=true]_&]:!flex min-[841px]:[[data-sidebar-collapsed=true]_&]:w-[38px] min-[841px]:[[data-sidebar-collapsed=true]_&]:min-w-[38px] min-[841px]:[[data-sidebar-collapsed=true]_&]:justify-center min-[841px]:[[data-sidebar-collapsed=true]_&]:p-0" type="button" data-open-search aria-label="Search documentation"><span class="relative inline-block h-3.5 w-3.5 rounded-full border-[1.6px] border-current text-[var(--faint)] after:absolute after:-bottom-0.5 after:-right-1 after:h-[1.6px] after:w-[5px] after:rotate-45 after:rounded after:bg-current" aria-hidden="true"></span><span class="overflow-hidden text-ellipsis whitespace-nowrap min-[841px]:[[data-sidebar-collapsed=true]_&]:hidden" data-search-placeholder>Search</span><span class="inline-flex items-center gap-1 text-[10px] text-[var(--faint)] [&_kbd]:min-w-[22px] min-[841px]:[[data-sidebar-collapsed=true]_&]:hidden" data-key-combo aria-hidden="true"><kbd data-key-command>Ctrl</kbd><span>+</span><kbd>K</kbd></span></button>
    <?php if ($sections): ?>
    <details class="group relative mb-3.5 min-[841px]:[[data-sidebar-collapsed=true]_&]:hidden" data-section-menu>
      <summary class="flex min-h-11 cursor-pointer list-none select-none items-center gap-2.5 rounded-[var(--radius)] border border-[var(--border)] bg-[var(--surface)] px-3 py-[9px] text-[13.5px] font-semibold text-[var(--text-strong)] hover:border-[var(--border-strong)] hover:bg-[var(--surface-hover)] [&::-webkit-details-marker]:hidden" aria-label="Change documentation section"><?= $section_icon($current_section['icon'] ?? 'home', 'h-[15px] w-[15px]') ?><span class="min-w-0 flex-1 overflow-hidden text-ellipsis whitespace-nowrap"><?= $e($current_section['title'] ?? 'Overview') ?></span><span class="h-1.5 w-1.5 rotate-45 border-b-[1.5px] border-r-[1.5px] border-current text-[var(--faint)] transition-transform duration-150 group-open:-rotate-[135deg]" aria-hidden="true"></span></summary>
      <nav class="absolute inset-x-0 top-[calc(100%+6px)] z-40 grid gap-0.5 rounded-[var(--radius)] border border-[var(--border)] bg-[var(--surface-raised)] p-[5px] shadow-[var(--shadow-lg)]" aria-label="Documentation sections">
        <a class="flex gap-2.5 rounded-[var(--radius-sm)] px-2.5 py-[9px] hover:bg-[var(--surface-hover)] aria-[current=page]:bg-[var(--brand-soft)]" href="/" <?= $current_section === null ? 'aria-current="page"' : '' ?>><?= $section_icon('home', 'mt-[3px]') ?><span><strong class="block text-[13.5px] font-semibold text-[var(--text-strong)]">Overview</strong><small class="block text-[13px] leading-[1.45] text-[var(--muted)]"><?= $e($config['tagline']) ?></small></span></a>
        <?php foreach ($sections as $section): ?><a class="flex gap-2.5 rounded-[var(--radius-sm)] px-2.5 py-[9px] hover:bg-[var(--surface-hover)] aria-[current=page]:bg-[var(--brand-soft)]" href="<?= $e($section['url']) ?>" <?= ($current_section['path'] ?? '') === $section['path'] ? 'aria-current="page"' : '' ?>><?= $section_icon($section['icon'] ?? null, 'mt-[3px]') ?><span><strong class="block text-[13.5px] font-semibold text-[var(--text-strong)]"><?= $e($section['title']) ?></strong><?php if ($section['description']): ?><small class="block text-[13px] leading-[1.45] text-[var(--muted)]"><?= $e($section['description']) ?></small><?php endif; ?></span></a><?php endforeach; ?>
      </nav>
    </details>
    <?php endif; ?>
    <nav class="min-h-0 flex-1 overflow-y-auto px-1.5 pb-3 pt-0.5 min-[841px]:[[data-sidebar-collapsed=true]_&]:hidden" data-sidebar-nav><?= $render_tree($tree, $current_url) ?></nav>
    <div class="mt-auto flex items-center gap-0.5 border-t border-[var(--border)] px-0.5 pt-2.5 min-[841px]:[[data-sidebar-collapsed=true]_&]:justify-center min-[841px]:[[data-sidebar-collapsed=true]_&]:border-t-0" data-sidebar-bottom>
      <?php if ($config['github_url']): ?><a class="rounded-md px-2 py-1.5 text-sm font-medium text-[var(--muted)] hover:bg-[var(--surface-hover)] hover:text-[var(--text)] min-[841px]:[[data-sidebar-collapsed=true]_&]:hidden" data-sidebar-bottom-link href="<?= $e($config['github_url']) ?>" rel="noopener noreferrer">GitHub</a><?php endif; ?>
      <?php if (!empty($config['private_access'])): ?><a class="rounded-md px-2 py-1.5 text-sm font-medium text-[var(--muted)] hover:bg-[var(--surface-hover)] hover:text-[var(--text)] min-[841px]:[[data-sidebar-collapsed=true]_&]:hidden" data-sidebar-bottom-link href="/inventory">Inventory</a><?php endif; ?>
      <a class="rounded-md px-2 py-1.5 text-sm font-medium text-[var(--muted)] hover:bg-[var(--surface-hover)] hover:text-[var(--text)] min-[841px]:[[data-sidebar-collapsed=true]_&]:hidden" data-sidebar-bottom-link href="/graph">Graph</a>
      <?php if ($config['editor_enabled']): ?><a class="rounded-md px-2 py-1.5 text-sm font-medium text-[var(--muted)] hover:bg-[var(--surface-hover)] hover:text-[var(--text)] min-[841px]:[[data-sidebar-collapsed=true]_&]:hidden" data-sidebar-bottom-link href="/admin">Studio</a><?php endif; ?>
      <button class="ms-auto grid h-[34px] w-[34px] place-items-center rounded-[var(--radius-sm)] p-0 text-[var(--muted)] hover:bg-[var(--surface-hover)] hover:text-[var(--text)]" type="button" data-reader-preferences-toggle data-tooltip="Reading preferences" aria-label="Reading preferences"><span class="text-[13px] font-[750] tracking-[-.08em]" aria-hidden="true">A<span class="text-[10px]">a</span></span></button>
      <button class="ms-auto grid h-[34px] w-[34px] place-items-center rounded-[var(--radius-sm)] p-0 text-[var(--muted)] hover:bg-[var(--surface-hover)] hover:text-[var(--text)] min-[841px]:[[data-sidebar-collapsed=true]_&]:m-0" type="button" data-sidebar-collapse aria-label="Collapse navigation" aria-expanded="true"><span class="h-2.5 w-2.5 rotate-45 border-b-[1.5px] border-s-[1.5px] border-current transition-transform duration-150 min-[841px]:[[data-sidebar-collapsed=true]_&]:[transform:rotate(225deg)]" data-collapse-icon aria-hidden="true"></span></button>
      <button class="group grid h-[34px] w-[34px] place-items-center rounded-[var(--radius-sm)] p-0 text-[var(--muted)] hover:bg-[var(--surface-hover)] hover:text-[var(--text)] min-[841px]:[[data-sidebar-collapsed=true]_&]:hidden" type="button" data-theme-toggle aria-label="Change color theme"><svg class="h-4 w-4 group-data-[theme=light]:hidden group-data-[theme=dark]:hidden" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" aria-hidden="true"><circle cx="12" cy="12" r="8"/><path d="M12 4a8 8 0 0 1 0 16z" fill="currentColor" stroke="none" opacity=".35"/></svg><svg class="hidden h-4 w-4 group-data-[theme=light]:block" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" aria-hidden="true"><circle cx="12" cy="12" r="3.5"/><path d="M12 2v2M12 20v2M4.93 4.93l1.42 1.42M17.65 17.65l1.42 1.42M2 12h2M20 12h2M4.93 19.07l1.42-1.42M17.65 6.35l1.42-1.42"/></svg><svg class="hidden h-4 w-4 group-data-[theme=dark]:block" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M20.5 14.3A8.5 8.5 0 0 1 9.7 3.5 8.5 8.5 0 1 0 20.5 14.3z"/></svg></button>
    </div>
  </aside>
  <div class="mt-4 min-h-[calc(100vh-12px)] min-w-0 rounded-t-[18px] border border-b-0 border-[var(--border)] bg-[var(--bg)] shadow-[var(--shadow-sm)] max-[840px]:m-0 max-[840px]:min-h-[calc(100vh-var(--header))] max-[840px]:rounded-none max-[840px]:border-0 max-[840px]:shadow-none print:m-0 print:min-h-0 print:rounded-none print:border-0 print:shadow-none">
    <main id="main-content" class="mx-auto min-w-0 max-w-[calc(var(--content)+56px)] px-7 pb-28 pt-11 max-[1200px]:px-9 max-[1200px]:pb-[88px] max-[1200px]:pt-9 max-[840px]:px-[22px] max-[840px]:pb-[88px] max-[840px]:pt-7 print:max-w-none print:p-0 [[data-density=compact]_&]:pt-[22px] [[data-reading-width=compact]_&]:max-w-[760px] [[data-reading-width=wide]_&]:max-w-[1060px] min-[841px]:[[data-reader-focus=true]_&]:max-w-[min(1080px,100%)]" tabindex="-1">
      <?php if ($breadcrumbs): ?>
        <nav class="mb-8 text-[13px] text-[var(--faint)] print:hidden" data-breadcrumbs aria-label="Breadcrumb"><ol class="m-0 flex list-none flex-wrap gap-[7px] p-0">
        <?php foreach ($breadcrumbs as $index => $crumb): ?><li class="flex items-center"><?php if ($index > 0): ?><span class="mr-[7px] text-[var(--border-strong)]" aria-hidden="true">/</span><?php endif; ?><?php if ($crumb['url']): ?><a class="hover:text-[var(--text)]" href="<?= $e($crumb['url']) ?>"><?= $e($crumb['title']) ?></a><?php else: ?><span aria-current="page"><?= $e($crumb['title']) ?></span><?php endif; ?></li><?php endforeach; ?>
        </ol></nav>
      <?php endif; ?>
      <?php if ($headings): ?><details class="group sticky top-2.5 z-40 mb-[22px] hidden rounded-[var(--radius-md)] border border-[var(--border)] bg-[color-mix(in_srgb,var(--surface)_92%,transparent)] shadow-[var(--shadow-sm)] backdrop-blur-[14px] max-[1200px]:block max-[840px]:top-[calc(var(--header)+10px)] print:hidden" data-toc-mobile><summary class="flex cursor-pointer list-none items-center gap-2 px-3 py-2.5 text-[13px] font-[620] text-[var(--muted)] group-open:border-b group-open:border-[var(--border)] [&::-webkit-details-marker]:hidden"><span>On this page</span><span class="min-w-0 flex-1 overflow-hidden text-ellipsis whitespace-nowrap text-right font-[480] text-[var(--faint)]" data-toc-current aria-hidden="true"></span><span class="h-1.5 w-1.5 rotate-45 border-b-[1.5px] border-r-[1.5px] border-current text-[var(--faint)] transition-transform duration-150 group-open:-rotate-[135deg]" aria-hidden="true"></span></summary><nav class="max-h-[min(46vh,340px)] overflow-auto overscroll-contain"><ul class="m-0 list-none p-2"><?php foreach ($headings as $heading): ?><li><a class="block rounded-[5px] px-2 py-1.5 text-[13px] text-[var(--muted)] hover:bg-[var(--surface-subtle)] hover:text-[var(--brand-strong)] data-[active=true]:bg-[var(--surface-subtle)] data-[active=true]:text-[var(--brand-strong)] [@media(pointer:coarse)]:min-h-10 <?= (int) $heading['level'] === 3 ? 'pl-[18px]' : '' ?>" href="#<?= $e($heading['id']) ?>"><?= $e($heading['title']) ?></a></li><?php endforeach; ?></ul></nav></details><?php endif; ?>
      <?= $content ?>
    </main>
  </div>
  <aside class="sticky top-0 h-screen h-dvh overflow-y-auto py-6 pe-1.5 ps-2 text-sm text-[var(--muted)] max-[1200px]:hidden print:hidden min-[841px]:[[data-reader-layout=notebook]_&]:hidden min-[841px]:[[data-reader-focus=true]_&]:hidden" data-toc aria-label="On this page">
    <?php if ($headings): ?><div class="relative ps-0.5 pt-[54px]" data-toc-inner><p class="mb-3 flex items-center gap-2 text-sm font-[640] text-[var(--text)]"><span class="text-[15px] leading-none text-[var(--faint)]" aria-hidden="true">≡</span>On this page</p><nav><ul class="relative m-0 list-none p-0 before:absolute before:inset-y-1.5 before:[inset-inline-start:0] before:w-px before:bg-[var(--border)]"><span class="pointer-events-none absolute [inset-inline-start:0] top-0 z-10 h-5 w-0.5 rounded-full bg-[var(--brand)] opacity-0 transition-[transform,height,opacity] duration-150" data-toc-indicator aria-hidden="true"></span><?php foreach ($headings as $heading): ?><li><a class="block py-[5px] <?= (int) $heading['level'] === 3 ? 'ps-6' : 'ps-[13px]' ?> leading-[1.45] hover:text-[var(--brand-strong)] data-[active=true]:font-semibold data-[active=true]:text-[var(--brand-strong)]" href="#<?= $e($heading['id']) ?>"><?= $e($heading['title']) ?></a></li><?php endforeach; ?></ul></nav><a class="mt-[17px] flex justify-between border-t border-[var(--border)] pt-[13px] text-[var(--faint)]" href="#main-content">Back to top <span>↑</span></a><?php if ($config['editor_enabled']): ?><a class="mt-2 flex justify-between py-2 text-[var(--faint)]" href="/admin">Open in Studio <span>↗</span></a><?php endif; ?></div><?php endif; ?>
  </aside>
</div>
<button class="fixed bottom-3.5 right-3.5 z-[80] grid h-[34px] w-[34px] [transform:translateY(8px)] place-items-center rounded-full border border-[var(--border-strong)] bg-[color-mix(in_srgb,var(--surface)_92%,transparent)] text-base leading-none text-[var(--text-strong)] opacity-0 shadow-[var(--shadow-sm)] backdrop-blur-lg transition-[opacity,transform,background] duration-150 hover:bg-[var(--surface-hover)] pointer-events-none min-[841px]:bottom-5 min-[841px]:right-5" type="button" data-back-to-top aria-label="Back to top" data-tooltip-placement="left"><span aria-hidden="true">↑</span></button>
<button class="fixed right-[35px] top-[30px] z-[85] hidden min-h-8 items-center gap-2 rounded-[var(--radius-sm)] border border-[var(--border-strong)] bg-[color-mix(in_srgb,var(--surface-raised)_94%,transparent)] px-[9px] py-1.5 text-[11px] font-[650] text-[var(--text-strong)] shadow-[var(--shadow-sm)] backdrop-blur-lg hover:bg-[var(--surface-hover)]" type="button" data-exit-reader-focus>Exit focus mode <kbd class="text-[10px] font-semibold text-[var(--faint)]">Esc</kbd></button>
<dialog class="mx-auto mt-[9vh] max-h-[76vh] w-[min(680px,calc(100vw_-_28px))] overflow-hidden rounded-[calc(var(--radius)+4px)] border border-[var(--border-strong)] bg-[var(--surface-raised)] p-0 text-[var(--text)] shadow-[var(--shadow-lg)] backdrop:bg-black/55 backdrop:backdrop-blur" data-search-dialog aria-label="Search documentation">
  <div>
    <div class="grid h-[57px] grid-cols-[18px_1fr_auto] items-center gap-2.5 border-b border-[var(--border)] px-3.5"><span class="relative inline-block h-3.5 w-3.5 rounded-full border-[1.6px] border-current text-[var(--faint)] after:absolute after:-bottom-0.5 after:-right-1 after:h-[1.6px] after:w-[5px] after:rotate-45 after:rounded after:bg-current" aria-hidden="true"></span><input class="w-full border-0 bg-transparent text-[15px] text-[var(--text-strong)] outline-none placeholder:text-[var(--faint)]" type="search" placeholder="Search pages and headings..." autocomplete="off" data-search-input><button class="cursor-pointer border-0 bg-transparent p-0" type="button" data-close-search aria-label="Close search"><kbd class="text-[10px] font-semibold text-[var(--faint)]">Esc</kbd></button></div>
    <div class="flex flex-wrap gap-1.5 px-3 pb-[3px] pt-2.5" data-search-filters hidden></div>
    <div class="max-h-[56vh] overflow-auto p-1.5" data-search-results><div class="flex min-h-[190px] flex-col items-center justify-center p-[30px] text-center text-[var(--muted)]"><span class="relative mb-3.5 h-9 w-9 rounded-[var(--radius-lg)] border border-[var(--border)] bg-[var(--surface-subtle)] before:absolute before:[inset-inline-start:10px] before:top-[9px] before:h-[11px] before:w-[11px] before:rounded-full before:border-[1.5px] before:border-[var(--faint)] after:absolute after:[inset-inline-start:20px] after:top-[21px] after:h-[1.5px] after:w-1.5 after:rotate-45 after:bg-[var(--faint)]" aria-hidden="true"></span><strong class="text-[var(--text-strong)]">Search the documentation</strong><p class="mt-1 text-[13px]">Find pages, commands, and individual sections.</p></div></div>
    <p class="sr-only" data-search-status aria-live="polite" aria-atomic="true"></p>
    <div class="flex h-[39px] items-center justify-end gap-3.5 border-t border-[var(--border)] bg-[var(--surface-subtle)] px-3 text-xs text-[var(--faint)] max-[540px]:justify-center [&>span]:flex [&>span]:items-center [&>span]:gap-[3px] [&>span:nth-child(2)]:max-[540px]:hidden [&_kbd]:min-h-4 [&_kbd]:px-1 [&_kbd]:py-px [&_kbd]:text-[11px]"><span><kbd>↑</kbd><kbd>↓</kbd> Navigate</span><span><kbd>Enter</kbd> Open</span><span><kbd>Esc</kbd> Close</span></div>
  </div>
</dialog>
<dialog class="m-auto max-h-[calc(100dvh_-_28px)] w-[min(420px,calc(100vw_-_28px))] overflow-hidden rounded-[calc(var(--radius)+2px)] border border-[var(--border)] bg-[var(--surface)] p-0 text-[var(--text)] shadow-[var(--shadow-lg)] backdrop:bg-black/40" data-reader-preferences-dialog aria-labelledby="reading-preferences-title">
  <form class="grid gap-4" method="dialog">
    <header class="flex items-center justify-between gap-3 border-b border-[var(--border)] px-[15px] py-[13px]"><div><p class="mb-0.5 text-[9px] font-semibold uppercase tracking-[.06em] text-[var(--brand-strong)]">Reader</p><strong class="text-[13px]" id="reading-preferences-title">Reading preferences</strong></div><button class="grid h-7 w-7 place-items-center rounded-md border border-[var(--border)] bg-[var(--surface-subtle)] text-[19px] leading-none text-[var(--text-strong)]" type="submit" aria-label="Close reading preferences">&times;</button></header>
    <fieldset class="grid gap-1.5 border-0 px-[15px]"><legend class="p-0 text-[11px] font-bold text-[var(--muted)]">Text size</legend><div class="grid grid-cols-3 gap-1.5"><label class="grid min-h-8 cursor-pointer place-items-center rounded-md border border-[var(--border)] bg-[var(--surface-subtle)] text-[11px] text-[var(--muted)] has-checked:border-[color-mix(in_srgb,var(--brand)_60%,var(--border))] has-checked:bg-[var(--brand-soft)] has-checked:font-semibold has-checked:text-[var(--brand-strong)]"><input class="pointer-events-none absolute opacity-0" type="radio" name="reading-text-size" value="small">Compact</label><label class="grid min-h-8 cursor-pointer place-items-center rounded-md border border-[var(--border)] bg-[var(--surface-subtle)] text-[11px] text-[var(--muted)] has-checked:border-[color-mix(in_srgb,var(--brand)_60%,var(--border))] has-checked:bg-[var(--brand-soft)] has-checked:font-semibold has-checked:text-[var(--brand-strong)]"><input class="pointer-events-none absolute opacity-0" type="radio" name="reading-text-size" value="default">Default</label><label class="grid min-h-8 cursor-pointer place-items-center rounded-md border border-[var(--border)] bg-[var(--surface-subtle)] text-[11px] text-[var(--muted)] has-checked:border-[color-mix(in_srgb,var(--brand)_60%,var(--border))] has-checked:bg-[var(--brand-soft)] has-checked:font-semibold has-checked:text-[var(--brand-strong)]"><input class="pointer-events-none absolute opacity-0" type="radio" name="reading-text-size" value="large">Large</label></div></fieldset>
    <fieldset class="grid gap-1.5 border-0 px-[15px]"><legend class="p-0 text-[11px] font-bold text-[var(--muted)]">Content width</legend><div class="grid grid-cols-3 gap-1.5"><label class="grid min-h-8 cursor-pointer place-items-center rounded-md border border-[var(--border)] bg-[var(--surface-subtle)] text-[11px] text-[var(--muted)] has-checked:border-[color-mix(in_srgb,var(--brand)_60%,var(--border))] has-checked:bg-[var(--brand-soft)] has-checked:font-semibold has-checked:text-[var(--brand-strong)]"><input class="pointer-events-none absolute opacity-0" type="radio" name="reading-content-width" value="compact">Compact</label><label class="grid min-h-8 cursor-pointer place-items-center rounded-md border border-[var(--border)] bg-[var(--surface-subtle)] text-[11px] text-[var(--muted)] has-checked:border-[color-mix(in_srgb,var(--brand)_60%,var(--border))] has-checked:bg-[var(--brand-soft)] has-checked:font-semibold has-checked:text-[var(--brand-strong)]"><input class="pointer-events-none absolute opacity-0" type="radio" name="reading-content-width" value="default">Default</label><label class="grid min-h-8 cursor-pointer place-items-center rounded-md border border-[var(--border)] bg-[var(--surface-subtle)] text-[11px] text-[var(--muted)] has-checked:border-[color-mix(in_srgb,var(--brand)_60%,var(--border))] has-checked:bg-[var(--brand-soft)] has-checked:font-semibold has-checked:text-[var(--brand-strong)]"><input class="pointer-events-none absolute opacity-0" type="radio" name="reading-content-width" value="wide">Wide</label></div></fieldset>
    <fieldset class="grid gap-1.5 border-0 px-[15px]"><legend class="p-0 text-[11px] font-bold text-[var(--muted)]">Layout</legend><div class="grid grid-cols-3 gap-1.5"><label class="grid min-h-8 cursor-pointer place-items-center rounded-md border border-[var(--border)] bg-[var(--surface-subtle)] text-[11px] text-[var(--muted)] has-checked:border-[color-mix(in_srgb,var(--brand)_60%,var(--border))] has-checked:bg-[var(--brand-soft)] has-checked:font-semibold has-checked:text-[var(--brand-strong)]"><input class="pointer-events-none absolute opacity-0" type="radio" name="reading-layout" value="standard">Standard</label><label class="grid min-h-8 cursor-pointer place-items-center rounded-md border border-[var(--border)] bg-[var(--surface-subtle)] text-[11px] text-[var(--muted)] has-checked:border-[color-mix(in_srgb,var(--brand)_60%,var(--border))] has-checked:bg-[var(--brand-soft)] has-checked:font-semibold has-checked:text-[var(--brand-strong)]"><input class="pointer-events-none absolute opacity-0" type="radio" name="reading-layout" value="notebook">Notebook</label><label class="grid min-h-8 cursor-pointer place-items-center rounded-md border border-[var(--border)] bg-[var(--surface-subtle)] text-[11px] text-[var(--muted)] has-checked:border-[color-mix(in_srgb,var(--brand)_60%,var(--border))] has-checked:bg-[var(--brand-soft)] has-checked:font-semibold has-checked:text-[var(--brand-strong)]"><input class="pointer-events-none absolute opacity-0" type="radio" name="reading-layout" value="focus">Focus</label></div><small class="text-[10.5px] text-[var(--muted)]">Notebook keeps compact navigation; Focus hides surrounding navigation.</small></fieldset>
    <footer class="flex items-center justify-between gap-3 border-t border-[var(--border)] px-[15px] py-[13px]"><button class="bg-transparent py-1.5 text-[11px] text-[var(--muted)]" type="button" data-reset-reading-preferences>Reset preferences</button><button class="rounded-[var(--radius-sm)] bg-[var(--brand)] px-3.5 py-2 text-sm font-semibold text-white hover:opacity-90" type="submit">Done</button></footer>
  </form>
</dialog>
</body>
</html>
