<article class="min-w-0 print:[&_a]:text-black" data-docs-article>
  <header class="mb-10 border-b border-[var(--border)] pb-[30px] pt-1"><div class="mb-3 flex items-center gap-2 text-xs font-semibold uppercase tracking-[.06em] text-[var(--brand-strong)]"><span>Documentation</span></div><h1 class="m-0 max-w-[760px] text-[clamp(2rem,4vw,2.72rem)] font-[760] leading-[1.08] tracking-[-.045em] text-[var(--text-strong)] text-balance">Search</h1><p class="mt-[15px] max-w-[660px] text-[17px] leading-[1.65] text-[var(--muted)]">Find pages, sections, commands, and concepts across the documentation.</p></header>
  <form class="relative my-7 flex gap-2 max-[540px]:flex-col" action="/search" method="get"><span class="absolute left-3.5 top-3.5 inline-block h-3.5 w-3.5 rounded-full border-[1.6px] border-current text-[var(--faint)] after:absolute after:-bottom-0.5 after:-right-1 after:h-[1.6px] after:w-[5px] after:rotate-45 after:rounded after:bg-current" aria-hidden="true"></span><input class="min-h-[42px] min-w-0 flex-1 rounded-[var(--radius-md)] border border-[var(--border)] bg-[var(--surface)] px-3 py-2 pl-10 outline-2 outline-transparent focus:border-[var(--brand)] focus:outline-[color-mix(in_srgb,var(--brand)_22%,transparent)]" type="search" name="q" value="<?= $e($query) ?>" placeholder="What are you looking for?" autofocus><button class="rounded-[var(--radius-sm)] bg-[var(--brand)] px-3.5 py-2 text-sm font-semibold text-white hover:opacity-90 max-[540px]:w-full" type="submit">Search</button></form>
  <?php if ($query !== ''): ?><p class="text-[13px] text-[var(--muted)]"><?= count($results) ?> result<?= count($results) === 1 ? '' : 's' ?> for “<?= $e($query) ?>”</p><?php endif; ?>
  <div class="grid gap-2">
  <?php foreach ($results as $result): ?><a class="relative flex flex-col rounded-[var(--radius-md)] border border-[var(--border)] bg-[var(--surface)] px-[15px] py-3.5 pr-[42px] shadow-sm hover:border-[color-mix(in_srgb,var(--brand)_36%,var(--border))]" href="<?= $e($result['url']) ?>"><span class="absolute right-4 top-1/2 [transform:translateY(-50%)] text-[var(--faint)]" aria-hidden="true">→</span><strong class="text-sm"><?= $e($result['title']) ?></strong><span class="text-xs text-[var(--muted)]"><?= $e($result['description']) ?></span></a><?php endforeach; ?>
  <?php if ($query !== '' && !$results): ?><div class="rounded-[calc(var(--radius)+2px)] border border-dashed border-[var(--border-strong)] bg-[var(--surface-subtle)] px-5 py-[55px] text-center"><span class="relative mx-auto mb-[15px] block h-9 w-9 rounded-[var(--radius-lg)] border border-[var(--border)] bg-[var(--surface-subtle)] before:absolute before:left-2.5 before:top-[9px] before:h-[11px] before:w-[11px] before:rounded-full before:border-[1.5px] before:border-[var(--faint)] after:absolute after:left-5 after:top-[21px] after:h-[1.5px] after:w-1.5 after:rotate-45 after:bg-[var(--faint)]" aria-hidden="true"></span><h2 class="m-0">No results found</h2><p class="mt-1 text-[var(--muted)]">Try fewer words or a broader phrase.</p></div><?php endif; ?>
  </div>
</article>
