<?= $header ?>
<div class="flex min-h-screen items-start bg-background" data-editor-shell>
  <aside class="sticky top-14 flex max-h-[calc(100vh-3.5rem)] shrink-0 grow-0 basis-[16rem] flex-col gap-3 overflow-visible border-e border-border bg-background p-4 text-xs aria-hidden:hidden max-[900px]:fixed max-[900px]:inset-y-0 max-[900px]:start-0 max-[900px]:z-[45] max-[900px]:max-h-none" id="studio-content-panel" aria-label="Content browser" aria-hidden="false">
    <div class="flex items-center justify-between gap-2">
      <div><span class="m-0 block text-xs font-bold uppercase tracking-[0.08em] text-muted-foreground">Workspace</span><strong class="block text-sm font-semibold">Content</strong></div>
      <a class="inline-flex min-h-9 items-center justify-center gap-1.5 rounded-lg border border-primary bg-primary px-3 py-1.5 text-xs font-semibold text-primary-foreground shadow-sm transition-colors hover:bg-primary/90" href="/admin/editor" aria-label="Create page"><svg class="h-4 w-4" viewBox="0 0 24 24" aria-hidden="true" fill="none" stroke="currentColor" stroke-width="2"><path d="M12 5v14M5 12h14"/></svg><span>New page</span></a>
    </div>
    <div class="flex min-h-0 flex-1 flex-col gap-4">
    <div>
          <input class="min-h-9 w-full rounded-md border border-input bg-card px-2.5 py-2 text-sm text-foreground" type="search" placeholder="Filter pages…" data-content-filter autocomplete="off" aria-label="Filter pages">
    </div>
    <div class="scrollbar-thin scrollbar-thumb-muted-foreground/30 scrollbar-track-transparent min-h-0 flex-1 overflow-y-auto pe-1"><nav aria-label="Documentation pages"><?= $editor_tree ?></nav></div>
    </div>
    <div class="grid shrink-0 gap-3">
    <details class="group border-t border-border pt-2.5" <?= $selected_is_snippet ? 'open' : '' ?>>
      <summary class="flex cursor-pointer list-none items-center justify-between gap-2 py-1 text-xs font-semibold [&::-webkit-details-marker]:hidden"><span><span class="me-1 font-mono text-muted-foreground" aria-hidden="true">{ }</span>Snippets</span><small class="font-medium text-muted-foreground"><?= count($snippets) ?></small><svg class="h-3.5 w-3.5 shrink-0 text-muted-foreground transition-transform" viewBox="0 0 24 24" aria-hidden="true" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="m6 9 6 6 6-6"/></svg></summary>
      <div class="grid gap-2 pt-2">
        <nav>
          <?php foreach ($snippets as $snippet): ?>
            <a class="flex w-full flex-col items-start gap-0.5 rounded-md border border-border bg-card px-2.5 py-1.5 text-xs font-semibold text-foreground transition-colors hover:bg-accent hover:text-accent-foreground aria-[current=page]:bg-accent aria-[current=page]:text-accent-foreground" href="<?= $e($snippet['url']) ?>" <?= $snippet['selected'] ? 'aria-current="page"' : '' ?>><span><?= $e($snippet['title']) ?></span><small><?= $snippet['usage_count'] ?> use<?= $snippet['usage_count'] === 1 ? '' : 's' ?></small></a>
          <?php endforeach; ?>
          <?php if (!$snippets): ?><p>No snippets yet.</p><?php endif; ?>
        </nav>
        <a class="mt-1 block text-xs font-semibold text-primary" href="/admin/editor?file=_snippets%2Fnew-snippet.md">New snippet</a>
      </div>
    </details>
    <details class="group border-t border-border pt-2.5">
      <summary class="flex cursor-pointer list-none items-center justify-between gap-2 py-1 text-xs font-semibold [&::-webkit-details-marker]:hidden"><span>Assets</span><small class="font-medium text-muted-foreground"><?= count($assets) ?></small><svg class="h-3.5 w-3.5 shrink-0 text-muted-foreground transition-transform" viewBox="0 0 24 24" aria-hidden="true" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="m6 9 6 6 6-6"/></svg></summary>
      <div class="grid gap-2 pt-2">
        <div class="grid gap-1">
          <?php foreach ($assets as $asset): ?>
            <button class="flex w-full flex-col items-start gap-0.5 rounded-md border border-border bg-card px-2.5 py-1.5 text-xs font-semibold leading-5 text-foreground transition-colors hover:bg-accent hover:text-accent-foreground" type="button" data-insert-asset="<?= $e($asset['url']) ?>"><span><?= $e($asset['name']) ?></span><small><?= $e($asset['size_label']) ?> · <?= $asset['usage_count'] ?> use<?= $asset['usage_count'] === 1 ? '' : 's' ?></small></button>
          <?php endforeach; ?>
          <?php if (!$assets): ?><p>No uploaded assets.</p><?php endif; ?>
        </div>
        <form method="post" enctype="multipart/form-data" class="mt-2 grid gap-2" data-upload-form>
          <input type="hidden" name="csrf_token" value="<?= $e($csrf) ?>">
          <input type="hidden" name="action" value="upload">
          <input type="hidden" name="file" value="<?= $e($selected) ?>">
          <div role="group" class="grid gap-0.5 rounded-md border border-dashed border-border p-2.5 text-xs"><label for="editor-asset-upload">Upload asset</label><p>Images, PDF, or text</p><input class="min-h-9 w-full rounded-md border border-input bg-card px-2.5 py-2 text-sm text-foreground" id="editor-asset-upload" type="file" name="asset" required></div>
          <button type="submit" class="inline-flex items-center justify-center gap-2 rounded-md border border-primary bg-primary px-3 py-1.5 text-sm font-semibold leading-5 text-primary-foreground transition-colors hover:bg-primary/90">Upload</button>
        </form>
      </div>
    </details>
    <div class="flex shrink-0 items-center gap-2 rounded-lg border border-border bg-card px-3 py-2 text-xs text-muted-foreground shadow-sm"><span class="inline-flex h-2 w-2 shrink-0 rounded-full bg-green-500"></span><span class="grid gap-0.5"><strong class="text-foreground">Index synced</strong><small><?= (int) ($index_stats['documents'] ?? 0) ?> docs · <?= (int) ($index_stats['keywords'] ?? 0) ?> keywords · <?= (int) ($index_stats['links'] ?? 0) ?> links</small></span></div>
    </div>

  </aside>
  <button type="button" class="editor-drawer-backdrop" data-close-content aria-label="Close content browser"></button>
  <main class="min-w-0 flex-1 px-6 pb-10 pt-5 text-sm">
    <?php if ($message): ?><div class="rounded-lg border border-border bg-card px-4 py-3 text-sm text-foreground" role="status"><?= $e($message) ?></div><?php endif; ?>
    <?php if ($error): ?><div class="rounded-lg border border-destructive/40 bg-destructive/10 px-4 py-3 text-sm text-destructive" role="alert"><?= $e($error) ?></div><?php endif; ?>
    <form method="post" class="grid gap-4" data-editor-form data-content-kind="<?= $selected_is_snippet ? 'snippet' : 'page' ?>">
      <input type="hidden" name="csrf_token" value="<?= $e($csrf) ?>">
      <input type="hidden" name="hash" value="<?= $e($source['hash']) ?>">
      <input type="hidden" name="action" value="save">
      <?php if ($selected === ''): ?>
        <nav class="flex flex-wrap items-center gap-2 text-sm" aria-label="Page template">
          <span>Start from</span>
          <div class="isolate inline-flex w-fit items-stretch [&>*:not(:first-child)]:-ms-px [&>*:not(:first-child)]:rounded-s-none [&>*:not(:last-child)]:rounded-e-none" role="group">
            <?php foreach ($templates as $template): ?><a href="<?= $e($template['url']) ?>" class="inline-flex items-center justify-center gap-2 rounded-md border px-3 py-1.5 text-sm font-semibold leading-5 transition-colors <?= $template['key'] === $selected_template ? 'border-primary bg-primary text-primary-foreground hover:bg-primary/90' : 'border-border bg-card text-foreground hover:bg-accent hover:text-accent-foreground' ?>"><?= $e($template['label']) ?></a><?php endforeach; ?>
          </div>
        </nav>
      <?php endif; ?>
      <div class="flex flex-wrap items-center gap-2 rounded-xl border border-border bg-card p-2 shadow-sm">
        <button class="inline-flex items-center justify-center gap-2 rounded-md border px-3 py-1.5 text-sm font-semibold leading-5 transition-colors border-border bg-card text-foreground hover:bg-accent hover:text-accent-foreground" type="button" data-toggle-content aria-controls="studio-content-panel" aria-expanded="true"><span aria-hidden="true">☰</span><span>Content</span></button>
        <div role="group" class="flex min-w-0 flex-1 items-center gap-2" data-orientation="horizontal"><label class="text-xs text-muted-foreground" for="editor-path">Path</label><input class="min-h-9 w-full rounded-lg border border-input bg-background px-2.5 py-2 font-mono text-xs text-foreground outline-none" id="editor-path" name="file" value="<?= $e($selected) ?>" placeholder="guides/new-page.md" required></div>
        <div class="flex flex-wrap items-center gap-2">
          <span class="text-xs text-muted-foreground" data-editor-count></span>
          <?php if (!$selected_is_snippet): ?><button class="inline-flex items-center justify-center gap-2 rounded-md border px-2 py-0.5 text-xs font-semibold leading-5 transition-colors border-border bg-card text-foreground hover:bg-accent hover:text-accent-foreground" type="button" data-toggle-metadata aria-expanded="false" aria-controls="editor-metadata">Details</button><?php endif; ?>
          <button class="inline-flex items-center justify-center gap-2 rounded-md border px-2 py-0.5 text-xs font-semibold leading-5 transition-colors border-border bg-card text-foreground hover:bg-accent hover:text-accent-foreground" type="button" data-toggle-preview aria-pressed="false">Preview only</button>
          <?php if ($git_file_history): ?><button class="inline-flex items-center justify-center gap-2 rounded-md border px-2 py-0.5 text-xs font-semibold leading-5 transition-colors border-border bg-card text-foreground hover:bg-accent hover:text-accent-foreground" type="button" data-toggle-git-history>History <span class="inline-flex min-h-6 w-fit items-center justify-center rounded-full px-2 py-0.5 text-xs font-semibold bg-muted text-muted-foreground"><?= count($git_file_history) ?></span></button><?php endif; ?>
          <div class="relative">
            <button class="inline-flex items-center justify-center gap-2 rounded-md border px-2 py-0.5 text-xs font-semibold leading-5 transition-colors border-border bg-card text-foreground hover:bg-accent hover:text-accent-foreground" type="button" id="editor-more-trigger" aria-haspopup="menu" aria-controls="editor-more-menu" aria-expanded="false">More</button>
            <div class="absolute right-0 top-[calc(100%+0.375rem)] z-[60] min-w-48 max-w-[calc(100vw-1rem)] overflow-hidden rounded-lg border border-border bg-popover p-1 text-popover-foreground shadow-xl aria-hidden:hidden" data-popover aria-hidden="true">
              <div class="grid gap-0.5" id="editor-more-menu" role="menu" aria-labelledby="editor-more-trigger">
                <?php if ($preview_url): ?><a role="menuitem" href="<?= $e($preview_url) ?>" target="_blank">Share preview</a><?php endif; ?>
                <?php if ($revisions): ?><button type="button" role="menuitem" data-toggle-revisions>Revisions <span><?= count($revisions) ?></span></button><?php endif; ?>
                <?php if (!$selected_is_snippet): ?><button type="button" role="menuitem" data-duplicate-page>Duplicate page</button><?php endif; ?>
              </div>
            </div>
          </div>
          <span class="flex items-center gap-1.5 text-xs text-muted-foreground" aria-live="polite"><span class="inline-flex h-2 w-2 rounded-full bg-green-500"></span><span data-save-state>Saved</span></span>
          <button class="inline-flex items-center justify-center gap-2 rounded-md border border-primary bg-primary px-3 py-1.5 text-sm font-semibold leading-5 text-primary-foreground transition-colors hover:bg-primary/90" type="submit">Save</button>
        </div>
      </div>
      <?php if ($selected_is_snippet): ?>
        <section class="grid gap-4 rounded-lg border border-border bg-card p-5 text-card-foreground shadow-sm mb-4">
          <div class="p-4"><strong>Used by <?= count($snippet_usages) ?> page<?= count($snippet_usages) === 1 ? '' : 's' ?></strong><span>Detected from include directives.</span></div>
          <nav class="flex w-full flex-col gap-2 p-4" role="list">
            <?php foreach ($snippet_usages as $usage): ?><a role="listitem" class="flex w-full flex-col justify-center gap-1 rounded-md border border-border bg-card p-3 text-sm transition-colors hover:bg-accent hover:text-accent-foreground" href="<?= $e($usage['url']) ?>"><section><h3><?= $e($usage['title']) ?></h3><p><?= $e($usage['relative_path']) ?></p></section></a><?php endforeach; ?>
            <?php if (!$snippet_usages): ?><span class="text-xs text-muted-foreground">This snippet is not currently used.</span><?php endif; ?>
          </nav>
        </section>
      <?php else: ?>
        <section id="editor-metadata" class="grid gap-4 rounded-lg border border-border bg-card p-4 text-xs text-card-foreground shadow-sm mb-4" data-metadata-panel hidden>
          <div class="grid grid-cols-[repeat(auto-fit,minmax(11rem,1fr))] gap-3">
            <div role="group" class="grid min-w-0 gap-1.5"><label for="meta-title">Title</label><input class="min-h-9 w-full rounded-md border border-input bg-card px-2.5 py-2 text-sm text-foreground" id="meta-title" type="text" value="<?= $e($editor_meta['title'] ?? '') ?>" data-meta-field="title"></div>
            <div role="group" class="grid min-w-0 gap-1.5"><label for="meta-description">Description</label><input class="min-h-9 w-full rounded-md border border-input bg-card px-2.5 py-2 text-sm text-foreground" id="meta-description" type="text" value="<?= $e($editor_meta['description'] ?? '') ?>" data-meta-field="description"></div>
          </div>
          <div class="grid grid-cols-[repeat(auto-fit,minmax(11rem,1fr))] gap-3">
            <div role="group" class="grid min-w-0 gap-1.5"><label for="meta-keywords">Keywords</label><input class="min-h-9 w-full rounded-md border border-input bg-card px-2.5 py-2 text-sm text-foreground" id="meta-keywords" type="text" list="known-keywords" value="<?= $e($editor_meta['keywords_value']) ?>" data-meta-field="keywords" placeholder="storage, backup, lxc"><datalist id="known-keywords"><?php foreach ($keyword_stats as $keyword): ?><option value="<?= $e($keyword['name']) ?>"><?= (int) $keyword['usage_count'] ?> uses</option><?php endforeach; ?></datalist></div>
            <div role="group" class="grid min-w-0 gap-1.5"><label for="meta-aliases">Redirect aliases</label><input class="min-h-9 w-full rounded-md border border-input bg-card px-2.5 py-2 text-sm text-foreground" id="meta-aliases" type="text" value="<?= $e($editor_meta['aliases_value']) ?>" data-meta-field="aliases" placeholder="/old-path"></div>
          </div>
          <div class="grid grid-cols-[repeat(auto-fit,minmax(8rem,1fr))] gap-3">
            <div role="group" class="grid min-w-0 gap-1.5"><label for="meta-order">Order</label><input class="min-h-9 w-full rounded-md border border-input bg-card px-2.5 py-2 text-sm text-foreground" id="meta-order" type="number" value="<?= $e($editor_meta['order'] ?? 100) ?>" data-meta-field="order"></div>
            <div role="group" class="grid min-w-0 gap-1.5"><label for="meta-status">Status</label><select class="min-h-9 w-full rounded-md border border-input bg-card px-2.5 py-2 text-sm text-foreground" id="meta-status" data-meta-field="status"><option value="draft" <?= ($editor_meta['status'] ?? (!empty($editor_meta['draft']) ? 'draft' : 'published')) === 'draft' ? 'selected' : '' ?>>Draft</option><option value="review" <?= ($editor_meta['status'] ?? '') === 'review' ? 'selected' : '' ?>>In review</option><option value="published" <?= ($editor_meta['status'] ?? (!empty($editor_meta['draft']) ? 'draft' : 'published')) === 'published' ? 'selected' : '' ?>>Published</option><option value="archived" <?= ($editor_meta['status'] ?? '') === 'archived' ? 'selected' : '' ?>>Archived</option></select></div>
            <div role="group" class="grid min-w-0 gap-1.5"><label for="meta-visibility">Visibility</label><select class="min-h-9 w-full rounded-md border border-input bg-card px-2.5 py-2 text-sm text-foreground" id="meta-visibility" data-meta-field="visibility"><option value="public" <?= ($editor_meta['visibility'] ?? 'public') === 'public' ? 'selected' : '' ?>>Public</option><option value="private" <?= ($editor_meta['visibility'] ?? '') === 'private' ? 'selected' : '' ?>>Private</option></select></div>
            <div role="group" class="grid min-w-0 gap-1.5"><label for="meta-type">Type</label><select class="min-h-9 w-full rounded-md border border-input bg-card px-2.5 py-2 text-sm text-foreground" id="meta-type" data-meta-field="type"><option value="article" <?= ($editor_meta['type'] ?? 'article') === 'article' ? 'selected' : '' ?>>Article</option><option value="runbook" <?= ($editor_meta['type'] ?? '') === 'runbook' ? 'selected' : '' ?>>Runbook</option></select></div>
            <div role="group" class="grid min-w-0 gap-1.5"><label for="meta-publish-at">Publish at</label><input class="min-h-9 w-full rounded-md border border-input bg-card px-2.5 py-2 text-sm text-foreground" id="meta-publish-at" type="datetime-local" value="<?= $e($editor_meta['publish_at_value']) ?>" data-meta-field="publish_at"></div>
            <div role="group" class="grid min-w-0 gap-1.5"><label for="meta-reviewed">Reviewed</label><input class="min-h-9 w-full rounded-md border border-input bg-card px-2.5 py-2 text-sm text-foreground" id="meta-reviewed" type="date" value="<?= $e($reviewed_value) ?>" data-meta-field="reviewed"></div>
            <div role="group" class="grid min-w-0 gap-1.5"><label for="meta-review-after">Review after</label><input class="min-h-9 w-full rounded-md border border-input bg-card px-2.5 py-2 text-sm text-foreground" id="meta-review-after" type="number" min="1" value="<?= $e($editor_meta['review_after'] ?? 180) ?>" data-meta-field="review_after"></div>
          </div>
          <div class="grid grid-cols-[repeat(auto-fit,minmax(14rem,1fr))] gap-2">
            <div role="group" class="flex items-center justify-between gap-3" data-orientation="horizontal"><input type="checkbox" role="switch" class="relative h-5 w-9 shrink-0 cursor-pointer appearance-none rounded-full border border-input bg-muted transition-colors checked:border-primary checked:bg-primary after:absolute after:left-0.5 after:top-0.5 after:h-3.5 after:w-3.5 after:rounded-full after:bg-white after:transition-transform after:content-[''] checked:after:translate-x-4" id="flag-draft" data-meta-field="draft" <?= !empty($editor_meta['draft']) ? 'checked' : '' ?>><section><label for="flag-draft">Draft</label><p>Hidden from readers until published</p></section></div>
            <div role="group" class="flex items-center justify-between gap-3" data-orientation="horizontal"><input type="checkbox" role="switch" class="relative h-5 w-9 shrink-0 cursor-pointer appearance-none rounded-full border border-input bg-muted transition-colors checked:border-primary checked:bg-primary after:absolute after:left-0.5 after:top-0.5 after:h-3.5 after:w-3.5 after:rounded-full after:bg-white after:transition-transform after:content-[''] checked:after:translate-x-4" id="flag-nav" data-meta-field="nav" <?= ($editor_meta['nav'] ?? true) !== false ? 'checked' : '' ?>><section><label for="flag-nav">In navigation</label><p>Listed in the sidebar page tree</p></section></div>
            <div role="group" class="flex items-center justify-between gap-3" data-orientation="horizontal"><input type="checkbox" role="switch" class="relative h-5 w-9 shrink-0 cursor-pointer appearance-none rounded-full border border-input bg-muted transition-colors checked:border-primary checked:bg-primary after:absolute after:left-0.5 after:top-0.5 after:h-3.5 after:w-3.5 after:rounded-full after:bg-white after:transition-transform after:content-[''] checked:after:translate-x-4" id="flag-secrets" data-meta-field="contains_secrets" <?= !empty($editor_meta['contains_secrets']) ? 'checked' : '' ?>><section><label for="flag-secrets">Contains secrets</label><p>Redacted in sanitized exports; keep visibility private</p></section></div>
            <div role="group" class="flex items-center justify-between gap-3" data-orientation="horizontal"><input type="checkbox" role="switch" class="relative h-5 w-9 shrink-0 cursor-pointer appearance-none rounded-full border border-input bg-muted transition-colors checked:border-primary checked:bg-primary after:absolute after:left-0.5 after:top-0.5 after:h-3.5 after:w-3.5 after:rounded-full after:bg-white after:transition-transform after:content-[''] checked:after:translate-x-4" id="flag-ai-exclude" data-meta-field="ai_exclude" <?= !empty($editor_meta['ai_exclude']) ? 'checked' : '' ?>><section><label for="flag-ai-exclude">Exclude from AI</label><p>Left out of llms.txt exports</p></section></div>
          </div>
        </section>
        <section class="grid gap-0 rounded-lg border border-border bg-card text-sm text-card-foreground shadow-sm" data-multiple>
          <details class="group">
          <summary class="flex cursor-pointer list-none items-center justify-between gap-2 p-4 [&::-webkit-details-marker]:hidden"><span class="grid gap-0.5"><strong class="text-sm">Page intelligence</strong><small class="text-xs font-normal text-muted-foreground"><?= count($page_issues) ?> issues · <?= count($page_backlinks) ?> incoming · <?= count($page_outbound) ?> outgoing</small></span><svg class="h-3.5 w-3.5 shrink-0 text-muted-foreground transition-transform" viewBox="0 0 24 24" aria-hidden="true" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="m6 9 6 6 6-6"/></svg></summary>
          <nav class="flex w-full flex-col gap-2 px-4 pb-4" role="list">
            <?php foreach ($page_issues as $issue): ?><a role="listitem" href="#contents" class="flex w-full flex-col justify-center gap-1 rounded-md border border-border bg-card p-3 text-sm transition-colors hover:bg-accent hover:text-accent-foreground"><section><p><span class="<?= $issue['label_class'] ?>"><?= $e($issue['label']) ?></span> <?= $e($issue['message']) ?></p></section></a><?php endforeach; ?>
            <?php foreach ($page_backlinks as $page): ?><a role="listitem" href="<?= $e($page['url']) ?>" class="flex w-full flex-col justify-center gap-1 rounded-md border border-border bg-card p-3 text-sm transition-colors hover:bg-accent hover:text-accent-foreground"><section><p><span>Linked by</span> <?= $e($page['title']) ?></p></section></a><?php endforeach; ?>
            <?php foreach ($page_outbound as $page): ?><a role="listitem" href="<?= $e($page['url']) ?>" class="flex w-full flex-col justify-center gap-1 rounded-md border border-border bg-card p-3 text-sm transition-colors hover:bg-accent hover:text-accent-foreground"><section><p><span>Links to</span> <?= $e($page['title']) ?></p></section></a><?php endforeach; ?>
            <?php if (!$page_issues && !$page_backlinks && !$page_outbound): ?><div class="flex flex-col items-center justify-center gap-2 rounded-lg border border-dashed border-border p-8 text-center text-sm text-muted-foreground"><p>No issues or page relationships.</p></div><?php endif; ?>
          </nav>
          </details>
        </section>
      <?php endif; ?>
      <section class="grid gap-0 rounded-lg border border-border bg-card text-sm text-card-foreground shadow-sm" data-multiple>
        <details class="group">
        <summary class="flex cursor-pointer list-none items-center justify-between gap-2 p-4 [&::-webkit-details-marker]:hidden"><span class="grid gap-0.5"><strong class="text-sm">Insert content</strong><small class="text-xs font-normal text-muted-foreground">Directives, page links, and snippets</small></span><svg class="h-3.5 w-3.5 shrink-0 text-muted-foreground transition-transform" viewBox="0 0 24 24" aria-hidden="true" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="m6 9 6 6 6-6"/></svg></summary>
          <section class="grid grid-cols-[repeat(auto-fit,minmax(13rem,1fr))] items-end gap-2.5 px-4 pb-4" aria-label="Insert documentation content">
          <div role="group" class="grid min-w-0 gap-1.5"><label for="insert-directive">Directive</label><select class="min-h-9 w-full rounded-md border border-input bg-card px-2.5 py-2 text-sm text-foreground" id="insert-directive" data-insert-directive><option value="callout">Callout</option><option value="banner">Banner</option><option value="tabs">Tabs</option><option value="filetree">File tree</option><option value="figure">Figure</option><option value="inline-toc">Inline TOC</option><option value="code">Code frame</option><option value="comparison">Comparison</option><option value="details">Details</option></select><button class="inline-flex items-center justify-center gap-2 rounded-md border px-3 py-1.5 text-sm font-semibold leading-5 transition-colors border-border bg-card text-foreground hover:bg-accent hover:text-accent-foreground" type="button" data-insert-directive-button>Insert directive</button></div>
          <div role="group" class="grid min-w-0 gap-1.5"><label for="insert-page">Page link</label><select class="min-h-9 w-full rounded-md border border-input bg-card px-2.5 py-2 text-sm text-foreground" id="insert-page" data-insert-page><?php foreach ($files as $file): ?><option value="<?= $e($file) ?>"><?= $e($file) ?></option><?php endforeach; ?></select><button class="inline-flex items-center justify-center gap-2 rounded-md border px-3 py-1.5 text-sm font-semibold leading-5 transition-colors border-border bg-card text-foreground hover:bg-accent hover:text-accent-foreground" type="button" data-insert-page-button>Insert page link</button></div>
          <div role="group" class="grid min-w-0 gap-1.5"><label for="insert-snippet">Snippet</label><select class="min-h-9 w-full rounded-md border border-input bg-card px-2.5 py-2 text-sm text-foreground" id="insert-snippet" data-insert-snippet><?php foreach ($snippets as $snippet): ?><option value="<?= $e($snippet['path']) ?>"><?= $e($snippet['title']) ?></option><?php endforeach; ?></select><button class="inline-flex items-center justify-center gap-2 rounded-md border px-3 py-1.5 text-sm font-semibold leading-5 transition-colors border-border bg-card text-foreground hover:bg-accent hover:text-accent-foreground" type="button" data-insert-snippet-button>Include snippet</button></div>
          <div role="group" class="grid min-w-0 gap-1.5"><label for="insert-media">Media</label><button id="insert-media" class="inline-flex items-center justify-center gap-2 rounded-md border px-3 py-1.5 text-sm font-semibold leading-5 transition-colors border-border bg-card text-foreground hover:bg-accent hover:text-accent-foreground" type="button" data-open-asset-picker>Choose image</button></div>
        </section>
        </details>
      </section>
      <dialog id="editor-asset-picker" class="m-auto rounded-lg border border-border bg-popover p-0 text-popover-foreground shadow-xl" data-asset-picker aria-labelledby="editor-asset-picker-title" aria-describedby="editor-asset-picker-description" onclick="if (event.target === this) this.close()">
        <div class="sm:max-w-3xl">
          <header><div><h2 id="editor-asset-picker-title">Insert image</h2><p id="editor-asset-picker-description">Type <code>@image</code> in Markdown to open this picker.</p></div></header>
          <section>
            <div>
              <input class="min-h-9 w-full rounded-md border border-input bg-card px-2.5 py-2 text-sm text-foreground" type="search" placeholder="Search uploaded images" data-asset-picker-search autocomplete="off" aria-label="Search uploaded images">
            </div>
            <div class="grid grid-cols-[repeat(auto-fill,minmax(7rem,1fr))] gap-2.5 max-h-96 overflow-y-auto p-4" data-asset-picker-grid>
          <?php foreach ($assets as $asset): ?>
            <?php if ($asset['is_image']): ?><button class="grid w-full gap-1 text-center text-xs" type="button" data-asset-picker-item data-asset-url="<?= $e($asset['url']) ?>" data-asset-name="<?= $e($asset['name']) ?>" data-asset-search="<?= $e($asset['search']) ?>"><img class="h-20 w-full rounded-[calc(var(--radius-md)-2px)] object-cover" src="<?= $e($asset['url']) ?>" alt=""><span><?= $e($asset['name']) ?></span></button><?php endif; ?>
          <?php endforeach; ?>
          <?php if (!$has_image_assets): ?><div class="flex flex-col items-center justify-center gap-2 rounded-lg border border-dashed border-border p-8 text-center text-sm text-muted-foreground"><p>Upload an image in the Media library first.</p></div><?php endif; ?>
            </div>
          </section>
          <button class="inline-flex items-center justify-center gap-2 rounded-md border p-1.5 font-semibold leading-5 transition-colors border-transparent bg-transparent text-foreground hover:bg-accent hover:text-accent-foreground" type="button" data-close-asset-picker aria-label="Close image picker" data-tooltip="Close" data-side="left">×</button>
        </div>
      </dialog>
      <?php if ($revisions): ?>
          <section class="grid gap-4 rounded-lg border border-border bg-card p-5 text-card-foreground shadow-sm mb-4" data-revision-panel hidden>
        <header><div><h2>Revision history</h2><p>Compare or restore an earlier version.</p></div><div class="flex items-center justify-end gap-3"><button class="inline-flex items-center justify-center gap-2 rounded-md border p-1.5 font-semibold leading-5 transition-colors border-transparent bg-transparent text-foreground hover:bg-accent hover:text-accent-foreground" type="button" data-close-revisions aria-label="Close" data-tooltip="Close" data-side="left">×</button></div></header>
          <div class="flex w-full flex-col gap-2 p-4" data-revisions-list role="list">
            <?php foreach ($revisions as $revision): ?>
              <article class="flex w-full flex-wrap items-center justify-between gap-3 rounded-md border border-border bg-card p-3 text-sm" role="listitem"><section class="min-w-0 flex-1"><h3><?= $e($revision['modified_label']) ?></h3><p><?= $e($revision['size_label']) ?></p></section><aside class="isolate flex w-fit items-stretch [&>*:not(:first-child)]:-ms-px [&>*:not(:first-child)]:rounded-s-none [&>*:not(:last-child)]:rounded-e-none" role="group"><button class="inline-flex items-center justify-center gap-2 rounded-md border px-3 py-1.5 text-sm font-semibold leading-5 transition-colors border-border bg-card text-foreground hover:bg-accent hover:text-accent-foreground" type="button" data-compare-revision="<?= $e($revision['id']) ?>">Compare</button><button class="inline-flex items-center justify-center gap-2 rounded-md border px-3 py-1.5 text-sm font-semibold leading-5 transition-colors border-border bg-card text-foreground hover:bg-accent hover:text-accent-foreground" type="submit" name="action" value="restore:<?= $e($revision['id']) ?>" data-restore-revision>Restore</button></aside></article>
            <?php endforeach; ?>
          </div>
        </section>
      <?php endif; ?>
      <?php if ($git_file_history): ?>
        <section class="grid gap-4 rounded-lg border border-border bg-card p-5 text-card-foreground shadow-sm mb-4" data-git-history-panel hidden>
        <header><div><h2>Local Git history</h2><p>Committed versions of this Markdown note. Viewing a snapshot never changes the file.</p></div><div class="flex items-center justify-end gap-3"><button class="inline-flex items-center justify-center gap-2 rounded-md border p-1.5 font-semibold leading-5 transition-colors border-transparent bg-transparent text-foreground hover:bg-accent hover:text-accent-foreground" type="button" data-close-git-history aria-label="Close" data-tooltip="Close" data-side="left">&times;</button></div></header>
          <div class="flex w-full flex-col gap-2 p-4" role="list">
            <?php foreach ($git_file_history as $commit): ?>
              <article class="flex w-full flex-wrap items-center justify-between gap-3 rounded-md border border-border bg-card p-3 text-sm" role="listitem"><section class="min-w-0 flex-1"><h3><?= $e($commit['subject']) ?></h3><p><code><?= $e($commit['short']) ?></code> &middot; <?= $e($commit['author']) ?> &middot; <?= $e($commit['date_label']) ?></p></section><aside class="flex items-center"><button class="inline-flex items-center justify-center gap-2 rounded-md border px-3 py-1.5 text-sm font-semibold leading-5 transition-colors border-border bg-card text-foreground hover:bg-accent hover:text-accent-foreground" type="button" data-compare-git="<?= $e($commit['hash']) ?>" data-git-label="<?= $e($commit['short'] . ' · ' . $commit['subject']) ?>">Compare</button></aside></article>
            <?php endforeach; ?>
          </div>
        </section>
      <?php endif; ?>
      <div class="grid grid-cols-2 overflow-hidden rounded-xl border border-border bg-card shadow-sm max-[900px]:grid-cols-1">
        <div class="relative grid gap-0 border-e border-border bg-card text-card-foreground" data-source-pane>
          <div class="flex h-10 items-center justify-between gap-3 border-b border-border px-4 py-2 text-xs font-semibold uppercase tracking-wide text-muted-foreground"><span>Markdown</span><div class="flex min-w-0 items-center gap-2 font-normal"><span class="max-w-[15rem]" data-editor-outline aria-label="Page outline"></span><span class="hidden items-center gap-1.5 sm:flex"><kbd class="inline-flex h-5 items-center rounded border border-border bg-muted px-1.5 text-[10px] text-muted-foreground">/</kbd> commands <span aria-hidden="true">·</span> <kbd class="inline-flex h-5 items-center rounded border border-border bg-muted px-1.5 text-[10px] text-muted-foreground">Ctrl/Cmd + S</kbd></span></div></div>
          <label class="sr-only" for="contents">Markdown</label>
          <textarea class="min-h-[calc(100vh-20rem)] w-full resize-none rounded-none border-0 bg-card p-5 font-mono text-sm leading-[1.7] text-foreground outline-none max-[900px]:min-h-[32rem]" id="contents" name="contents" spellcheck="true" data-markdown-editor><?= $e($source['contents']) ?></textarea>
          <div class="absolute z-30 grid w-[min(22rem,calc(100vw-2rem))] min-w-0 max-w-full overflow-hidden rounded-lg border border-border bg-popover text-popover-foreground shadow-xl" data-slash-menu-root hidden aria-label="Insert Markdown content"><div class="grid gap-1 max-h-[min(18rem,45vh)] p-1" role="menu" data-slash-menu></div></div>
        <aside class="mt-2 flex items-center gap-2 rounded-lg border border-border bg-card px-4 py-3 text-sm text-foreground" data-glossary-suggestion hidden aria-live="polite"><span data-glossary-suggestion-label></span><button class="inline-flex items-center justify-center gap-2 rounded-md border px-2 py-0.5 text-xs font-semibold leading-5 transition-colors border-border bg-card text-foreground hover:bg-accent hover:text-accent-foreground" type="button" data-insert-glossary-reference>Add reference</button><button class="inline-flex items-center justify-center gap-2 rounded-md border p-1.5 font-semibold leading-5 transition-colors border-transparent bg-transparent text-foreground hover:bg-accent hover:text-accent-foreground" type="button" data-dismiss-glossary-suggestion aria-label="Dismiss glossary suggestion" data-tooltip="Dismiss" data-side="left">&times;</button></aside>
        </div>
        <div class="min-w-0 grid gap-0 bg-card text-card-foreground [&.is-expanded]:col-span-full [&.is-expanded]:mx-auto [&.is-expanded]:w-full [&.is-expanded]:max-w-[72rem]" data-preview-pane>
          <div class="flex h-10 items-center justify-between gap-2 border-b border-border px-4 py-2 text-xs font-semibold uppercase tracking-wide text-muted-foreground"><span>Preview</span><div role="group" class="isolate inline-flex h-6 w-fit items-stretch rounded-md border border-border bg-muted p-0.5" aria-label="Preview size"><button class="inline-flex h-5 items-center justify-center rounded px-1.5 text-[10px] font-medium leading-4 text-muted-foreground transition-colors hover:bg-card hover:text-foreground data-[variant=outline]:border data-[variant=outline]:border-border data-[variant=outline]:bg-card data-[variant=outline]:text-foreground" type="button" data-preview-size="desktop" data-variant="outline" aria-pressed="true">Desktop</button><button class="inline-flex h-5 items-center justify-center rounded px-1.5 text-[10px] font-medium leading-4 text-muted-foreground transition-colors hover:bg-card hover:text-foreground data-[variant=outline]:border data-[variant=outline]:border-border data-[variant=outline]:bg-card data-[variant=outline]:text-foreground" type="button" data-preview-size="tablet" data-variant="ghost" aria-pressed="false">Tablet</button><button class="inline-flex h-5 items-center justify-center rounded px-1.5 text-[10px] font-medium leading-4 text-muted-foreground transition-colors hover:bg-card hover:text-foreground data-[variant=outline]:border data-[variant=outline]:border-border data-[variant=outline]:bg-card data-[variant=outline]:text-foreground" type="button" data-preview-size="mobile" data-variant="ghost" aria-pressed="false">Mobile</button></div></div>
          <iframe class="min-h-[calc(100vh-20rem)] w-full rounded-md border border-border bg-white data-[size=tablet]:mx-auto data-[size=tablet]:w-[min(100%,48rem)] data-[size=mobile]:mx-auto data-[size=mobile]:w-[min(100%,24rem)] max-[900px]:min-h-[32rem]" title="Preview" data-preview-frame></iframe>
        </div>
      </div>
    </form>
  </main>
</div>
<script type="application/json" data-glossary-terms><?= $glossary_json ?: '[]' ?></script>
<dialog id="revision-compare-dialog" class="m-auto max-h-[90vh] w-[min(94vw,78rem)] max-w-none overflow-hidden rounded-xl border border-border bg-popover p-0 text-popover-foreground shadow-2xl" data-revision-compare aria-labelledby="revision-compare-title" onclick="if (event.target === this) this.close()"><div class="grid max-h-[90vh] gap-4 overflow-hidden p-5"><header class="flex items-center justify-between gap-4 border-b border-border pb-3"><div><p class="m-0 text-xs font-semibold uppercase tracking-wide text-muted-foreground">Editor</p><h2 id="revision-compare-title" class="mt-1 text-base font-semibold">Revision comparison</h2></div><button class="inline-flex h-7 w-7 shrink-0 items-center justify-center rounded-md text-lg leading-none text-muted-foreground transition-colors hover:bg-accent hover:text-foreground" type="button" data-close-compare aria-label="Close">×</button></header><section class="grid min-h-0 grid-cols-2 gap-4 max-[900px]:grid-cols-1"><div class="grid min-h-0 gap-2"><span class="text-xs font-semibold text-muted-foreground">Selected revision</span><pre class="min-h-48 max-h-[65vh] overflow-auto rounded-lg border border-border bg-muted p-3 text-xs leading-5" data-revision-source></pre></div><div class="grid min-h-0 gap-2"><span class="text-xs font-semibold text-muted-foreground">Current editor</span><pre class="min-h-48 max-h-[65vh] overflow-auto rounded-lg border border-border bg-muted p-3 text-xs leading-5" data-current-source></pre></div></section></div></dialog>
<dialog id="git-compare-dialog" class="m-auto max-h-[90vh] w-[min(94vw,78rem)] max-w-none overflow-hidden rounded-xl border border-border bg-popover p-0 text-popover-foreground shadow-2xl" data-git-compare aria-labelledby="git-compare-title" onclick="if (event.target === this) this.close()"><div class="grid max-h-[90vh] gap-4 overflow-hidden p-5"><header class="flex items-center justify-between gap-4 border-b border-border pb-3"><div><p class="m-0 text-xs font-semibold uppercase tracking-wide text-muted-foreground">Local Git</p><h2 id="git-compare-title" class="mt-1 text-base font-semibold">Local Git note comparison</h2></div><button class="inline-flex h-7 w-7 shrink-0 items-center justify-center rounded-md text-lg leading-none text-muted-foreground transition-colors hover:bg-accent hover:text-foreground" type="button" data-close-git-compare aria-label="Close">×</button></header><section class="grid min-h-0 grid-cols-2 gap-4 max-[900px]:grid-cols-1"><div class="grid min-h-0 gap-2"><span class="text-xs font-semibold text-muted-foreground" data-git-source-label>Committed version</span><pre class="min-h-48 max-h-[65vh] overflow-auto rounded-lg border border-border bg-muted p-3 text-xs leading-5" data-git-source></pre></div><div class="grid min-h-0 gap-2"><span class="text-xs font-semibold text-muted-foreground">Current editor</span><pre class="min-h-48 max-h-[65vh] overflow-auto rounded-lg border border-border bg-muted p-3 text-xs leading-5" data-git-current-source></pre></div></section></div></dialog>
<?= $footer ?>
