<?= $header ?>
<main class="mx-auto grid w-[min(calc(100%-3rem),82rem)] gap-6 py-7 pb-10 text-sm max-[900px]:w-[min(calc(100%-2rem),82rem)] max-[640px]:gap-5 max-[640px]:py-5">
  <header class="flex items-end justify-between gap-6 max-[640px]:items-stretch max-[640px]:flex-col"><div class="grid gap-1"><nav class="flex items-center gap-2 text-xs text-muted-foreground" aria-label="Breadcrumb"><a class="transition-colors hover:text-foreground" href="/admin">Workspace</a><svg class="h-3.5 w-3.5" viewBox="0 0 24 24" aria-hidden="true" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="m9 18 6-6-6-6"/></svg><a class="transition-colors hover:text-foreground" href="/admin/roles">Roles</a><svg class="h-3.5 w-3.5" viewBox="0 0 24 24" aria-hidden="true" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="m9 18 6-6-6-6"/></svg><span class="max-w-40 truncate text-foreground"><?= $create ? 'New role' : $e($selected['name']) ?></span></nav><h1 class="m-0 text-2xl font-semibold tracking-[-0.03em] text-foreground"><?= $create ? 'Add role' : $e($selected['name']) ?></h1><p class="m-0 text-sm leading-6 text-muted-foreground"><?= $create ? 'Create a focused access policy for Studio users.' : 'Review and update the permissions assigned to this role.' ?></p></div><a class="inline-flex min-h-9 items-center justify-center gap-2 rounded-md border border-border bg-card px-3.5 py-2 text-sm font-semibold leading-5 text-foreground shadow-sm transition-colors hover:bg-accent hover:text-accent-foreground max-[640px]:w-full" href="/admin/roles"><svg class="h-4 w-4" viewBox="0 0 24 24" aria-hidden="true" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="m15 18-6-6 6-6"/></svg><span>Back to roles</span></a></header>

  <?php if (!empty($message)): ?><div class="rounded-lg border border-border bg-card px-4 py-3 text-sm text-foreground shadow-sm" role="status"><?= $e($message) ?></div><?php endif; ?>
  <?php if (!empty($error)): ?><div class="rounded-lg border border-destructive/40 bg-destructive/10 px-4 py-3 text-sm text-destructive" role="alert"><?= $e($error) ?></div><?php endif; ?>

  <div class="grid grid-cols-[15rem_minmax(0,1fr)] items-start gap-5 max-[760px]:grid-cols-1">
    <aside class="grid gap-4 rounded-xl border border-border bg-card p-5 text-card-foreground shadow-sm max-[760px]:grid-cols-2 max-[560px]:grid-cols-1 max-[640px]:rounded-lg"><div class="grid justify-items-center gap-3 border-b border-border pb-5 text-center max-[760px]:justify-items-start max-[760px]:border-b-0 max-[760px]:border-r max-[760px]:pr-5 max-[560px]:justify-items-center max-[560px]:border-r-0 max-[560px]:border-b max-[560px]:pb-5 max-[560px]:pr-0"><span class="inline-flex h-16 w-16 items-center justify-center rounded-full bg-primary/10 text-xl font-semibold text-primary"><?= $create ? '?' : $e(mb_strtoupper(mb_substr($selected['name'], 0, 1))) ?></span><div class="grid gap-0.5"><strong class="text-base font-semibold text-foreground"><?= $create ? 'New role' : $e($selected['name']) ?></strong><span class="text-xs text-muted-foreground"><?= $create ? 'Access policy' : ($is_protected ? 'Built-in role' : 'Custom role') ?></span></div><?php if ($is_protected): ?><span class="inline-flex items-center gap-1.5 text-xs font-medium text-amber-700 dark:text-amber-300"><span class="h-1.5 w-1.5 rounded-full bg-amber-500"></span>Protected</span><?php else: ?><span class="inline-flex items-center gap-1.5 text-xs font-medium text-emerald-600 dark:text-emerald-400"><span class="h-1.5 w-1.5 rounded-full bg-emerald-500"></span>Editable policy</span><?php endif; ?></div><dl class="grid gap-3 text-xs max-[760px]:content-start max-[560px]:grid-cols-2"><div class="grid gap-0.5"><dt class="text-muted-foreground">Role ID</dt><dd class="m-0 font-medium text-foreground"><?= $create ? 'Not assigned' : '#' . (int)$selected['user_group_id'] ?></dd></div><div class="grid gap-0.5"><dt class="text-muted-foreground">Users</dt><dd class="m-0 font-medium text-foreground"><?= $create ? '0' : (int)$selected['user_count'] ?></dd></div><div class="grid gap-0.5"><dt class="text-muted-foreground">View areas</dt><dd class="m-0 font-medium text-foreground"><?= $create ? '0' : count($selected['permission']['access']) ?></dd></div><div class="grid gap-0.5"><dt class="text-muted-foreground">Modify areas</dt><dd class="m-0 font-medium text-foreground"><?= $create ? '0' : count($selected['permission']['modify']) ?></dd></div></dl></aside>

    <section class="overflow-hidden rounded-xl border border-border bg-card text-card-foreground shadow-sm max-[640px]:rounded-lg"><header class="border-b border-border px-5 py-4 max-[640px]:px-4"><p class="m-0 text-xs font-semibold uppercase tracking-wide text-muted-foreground"><?= $create ? 'New role' : 'Role settings' ?></p><h2 class="mt-1 text-base font-semibold tracking-[-0.01em] text-foreground"><?= $create ? 'Create an access policy' : 'Role details and permissions' ?></h2><p class="mt-1 text-xs leading-5 text-muted-foreground">Permissions are additive. Users receive changes on their next request.</p></header><?php if ($is_protected): ?><div class="mx-5 mt-4 flex gap-3 rounded-lg border border-amber-300 bg-amber-100 px-3.5 py-3 text-xs font-medium text-amber-950 dark:border-amber-800 dark:bg-amber-950/50 dark:text-amber-100 max-[640px]:mx-4" role="note"><svg class="mt-0.5 h-4 w-4 shrink-0" viewBox="0 0 24 24" aria-hidden="true" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M12 3 4 7v5c0 4.7 3.4 8.7 8 10 4.6-1.3 8-5.3 8-10V7l-8-4Z"/><path d="M12 8v4M12 16h.01"/></svg><p class="m-0 leading-5">This built-in role always has full access and cannot be edited.</p></div><?php endif; ?><form method="post" class="grid gap-0"><input type="hidden" name="csrf_token" value="<?= $e($csrf) ?>"><?= $role_fields ?><footer class="flex items-center justify-between gap-3 border-t border-border bg-muted/20 px-5 py-4 max-[560px]:items-stretch max-[560px]:flex-col max-[640px]:px-4"><span class="text-xs text-muted-foreground"><?= $create ? 'You can update permissions later.' : 'Review the changes before saving.' ?></span><div class="flex items-center gap-2 max-[560px]:flex-col-reverse"><a class="inline-flex min-h-9 items-center justify-center rounded-md border border-border bg-card px-3.5 py-2 text-sm font-semibold leading-5 text-foreground transition-colors hover:bg-accent hover:text-accent-foreground max-[560px]:w-full" href="/admin/roles">Cancel</a><button class="inline-flex min-h-9 items-center justify-center gap-2 rounded-md border border-primary bg-primary px-3.5 py-2 text-sm font-semibold leading-5 text-primary-foreground shadow-sm transition-colors hover:bg-primary/90 max-[560px]:w-full" type="submit"><svg class="h-4 w-4" viewBox="0 0 24 24" aria-hidden="true" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M19 21H5a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h11l5 5v11a2 2 0 0 1-2 2Z"/><path d="M17 21v-8H7v8M7 3v5h8"/></svg><span><?= $create ? 'Create role' : 'Save changes' ?></span></button></div></footer></form></section>
  </div>
</main>
<?= $footer ?>
